### PR TITLE
Present bed to printer front on stop print

### LINKED ISSUE #17: [FR] Present bed forward on print abort
### Description

When a user selects "Stop Print" from the menu during a print the bed should be presented to the front of the printer.

### Feature Workflow

1. Print in action
2. User selects "Stop Print" from the menu
3. Printer stops printing
4. Printer presents the bed to the front of the printer

### PR DESCRIPTION
**Pull request by mikejr83**
### Description

Modify the g-code in `EVENT_GCODE_SD_ABORT` to add a _G0_ command. This presents the bed forward.

### Benefits

Enables the user easy access to the print area.

### Related Issues

Closes #17.

### CODE REVIEW

**Comment by mikejr83** [comment]
Right now the g-code is modified to be:

```c
#define EVENT_GCODE_SD_ABORT "G28XY\nG0 Y" STRINGIFY(Y_BED_SIZE)      // G-code to run on SD Abort Print (e.g., "G28XY" or "G27")
```

I thought about adding g-code to disable steppers except for z.

We could go with it by modifying the commit to be:

```c
#define EVENT_GCODE_SD_ABORT "G28XY\nG0 Y" STRINGIFY(Y_BED_SIZE) "\nM84 X Y E"      // G-code to run on SD Abort Print (e.g., "G28XY" or "G27")
```

**Comment by mikejr83** [comment]
It looks like I need to add a feed rate parameter to the G0 command. Depending on when you stop the print the feed rate could be slow an the G0 takes a long time. Other than that in practice I like this functionality.

**Comment by attacktwinkie** [comment]
Is this ready to go as is? or do you need to add the parameterized GCODE?

**Comment by mikejr83** [comment]
I tested a few changes on my end and want to put them in. Give me a moment and I'll do that.

**Comment by mikejr83** [comment]
@attacktwinkie I updated the commit. The gcode now breaks down to this:

```
G28X ; moves carriages to their parked location
G0 Y310 F1500 ; moves the bed "forward" at a decent speed
M84 X Y E ; disable the steppers except for z
```

I exploded that out from the actual code, but the gist is move buckets to the side, move the head to the back (bed moves forward), and then disable the steppers except for z (so it doesn't fall down). I had the feed rate 3000 and it was shooting forward. I cut it in half.

**Review by attacktwinkie — APPROVED** [review]
This looks Great!  We'll merge it into 2021.1

**Pull request merged**
